services:
  - type: web
    name: bursary-mgt
    env: docker
    plan: free
    region: ohio
    dockerContext: .
    dockerfilePath: Dockerfile
    healthCheckPath: /
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://*.onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: bursary-db
          property: connectionString

databases:
  - name: bursary-db
    plan: free
    region: ohio
